name: Docs
on:
  pull_request:
    types: [synchronize, edited, opened]
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      check_result: ${{steps.check.outputs.result}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: poetry
      - name: Install Environment
        run: make setup
      - name: Build Documentation
        run: make html/fast LOGFILE=_build_html.log
      - name: Parse Build Logs
        id: check
        run: python check-build-logs.py _build_html.log "$GITHUB_OUTPUT"
      - name: Archive Documentation
        run: make archive/fast
      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: github-pages
          path: ${{github.workspace}}/cps-docs.tar
  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check Build Logs
        env:
          RESULT: ${{needs.build.outputs.check_result}}
        run: |
          exit $RESULT
  deploy:
    if: github.event.repository.default_branch == github.ref_name
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
